# Generated by Django 4.1.3 on 2022-11-12 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_rename_descripcion_task_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskModel',
        ),
    ]
