# Generated by Django 4.1.3 on 2022-11-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaTesisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='perfilmodel',
            name='tema',
        ),
    ]
